### ISSUE TITLE
Define timeline for goodtables.io EOL

### ISSUE THREAD

**Issue by sapetti9** [frictionlessdata/software#18]
Reminder that we need to think about this.
@amercader 
@lwinfree

**Comment by roll** [comment]
I think we can announce it after the successful migration (cc @aivuk)

**Comment by roll** [comment]
@sapetti9 
@lwinfree 
@aivuk 
Our migration is going well I think we can sent the second email next week. WDYT?

**Comment by aivuk** [comment]
I agree, all my tests at https://new.goodtables.io and https://try.new.goodtables.io were successful. I think we are good to go.

**Comment by lwinfree** [comment]
great!

**Comment by sapetti9** [comment]
Email sent.
