### ISSUE TITLE
Migrate Java libraries to Github Actions

### ISSUE THREAD

**Issue by roll** [frictionlessdata/software#21]
# Overview

We need to migrate from Travis CI to Github Actions:

- https://github.com/frictionlessdata/tableschema-java
- https://github.com/frictionlessdata/datapackage-java

**Comment by shashigharti** [comment]
@roll PR created and it is ready for review!
https://github.com/frictionlessdata/tableschema-java/pull/71
https://github.com/frictionlessdata/datapackage-java/pull/42

**Comment by roll** [comment]
Thanks!

**Comment by roll** [comment]
DONE
