### ISSUE TITLE
Update goodtables.io usage report

### ISSUE THREAD

**Issue by roll** [frictionlessdata/software#7]
We need new 2022 numbers compared to 2021

**Comment by roll** [comment]
@lwinfree 
@sapetti9 
@amercader 
https://docs.google.com/document/d/1Y14ASChdCh-h_IyEvSeIvmnoGKyydBISZfGutV3WMFk/edit#

Here is a 2-3x drop in usage after the @sapetti9's work on Frictionless Repository noticing

**Comment by lwinfree** [comment]
It is about to go up a lot because the fellows are using it, so if we do see an increase in the coming month, it is likely an artifact of the fellows.
