### ISSUE TITLE
Consider removing PRs from boards

### ISSUE THREAD

**Issue by roll** [frictionlessdata/software#8]
# Overview

Currently, Github Projects Beta has some limitations described in frictionlessdata/project#751 

One of them is that using Github Actions to add PRs to boards we miss all PRs from first contributors as they require approval to run actions. Also, Github doesn't merge an issue and a PR so there is a duplication (we archive excessive PRs ATM).

As it's a good practice to have an issue for every PR for proper analysis and discussion we might consider removing PR tracking from our boards at all managing them in the linked PRs issue's column.

**Comment by lwinfree** [comment]
Makes sense to me!

**Comment by roll** [comment]
But on the other hand,

- we have many PRs from our side not covered by any issue
- we also sometime get collaborator PRs when they don't create any issue
- the idea that we get notified about everything on our board feels good to me

As it's don't really hard for me to archive duplicate PRs I think keeping PRs on the board still will bring more additional value rather removing them save addition time.

I'm closing it for now, please re-open if you think we need to consider/discuss it more
