### ISSUE TITLE
Deprecate goodtables.io in favor of Frictionless Repository

### ISSUE THREAD

**Issue by roll** [frictionlessdata/software#9]
@lwinfree 
@sapetti9 
@amercader 
I think it's might be a time to send an email notification to the userbase about goodtables.io's EOL (e.g. end of 2022?)

**Comment by roll** [comment]
@sapetti9 
https://docs.google.com/document/d/1Y14ASChdCh-h_IyEvSeIvmnoGKyydBISZfGutV3WMFk/edit#heading=h.6cd8b6jhfkxw

**Comment by sapetti9** [comment]
Done.
